---
title: "Research Blog"
output: html_document
---

[Home](index.html)  |  [Research](research.html)  |  [Publications](pubs.html)  |  [Outreach](outreach.html)  |  [About](about.html) | [Blog](blog.html) | [Gallery](gallery.html)

#### Research Updates:

**January 2022:** I am here at UC Riverside to work on projects related to the bee gut microbiome with [Dr. Quinn McFrederick](https://melittology.ucr.edu/). I have already learned so much already and am looking forward to seeing what we find! 

Also, our paper about how sunflower affects a gut pathogen in multiple bumble bee species has been accepted for publication in *Proceedings of the Royal Society B*. I hope to share the final version soon! 

**November 2021:** Our paper about how sunflower affects the bumble bee immune system has been accepted for publication as part of a special issue in *Philosophical Transactions B*. I think we will be able to share the final version when the issue comes out in March 2022. 

**October 2020:** [Wrapping up summer field work](blog_1.html)

#### Some notes on what I've been working on, thinking about, reading, etc.:

[Some of my favorite popular science books](blog_2.html),
updated April 26, 2021

[Maps are the Ultimate Scientific Tool](http://thatslifesci.com/2021-03-29-maps-are-the-ultimate-scientific-tool-afowler/), posted to **That's Life [Science]** March 29, 2021

[Nurturing Our Offline Selves](http://thatslifesci.com/2021-02-15-Offline-Self-AFowler/),
posted to **That's Life [Science]** February 15, 2021

[It's Not Science Fiction; Chimeras are Real](http://thatslifesci.com/2019-06-24-Chimeras-Are-Real-AFowler/),
inspired by a chapter of Carl Zimmer's *She Has Her Mother's Laugh*, posted to **That's Life [Science]** June 24, 2019

