---
title: "Publications"
output: html_document
---

[Home](index.html)  |  [Research](research.html)  |  [Publications](pubs.html)  |  [Outreach](outreach.html)  |  [About](about.html) | [Blog](blog.html) | [Gallery](gallery.html) 

[Google scholar](https://scholar.google.com/citations?user=tSQCC-QAAAAJ&hl=en) <br/>

**Fowler AE**, Kola E, Adler LS. The effect of sunflower pollen age and origin on pathogen infection in the common eastern bumble bee (Apidae: Hymenoptera). *Journal of Economic Entomology*. In Press.

Figueroa LL, **Fowler AE**, Lopez S, Amaral VE, Koch H, Stevenson PC, Irwin RE, Adler LS. 2023. Sunflower spines and beyond: mechanisms and breadth of pollen that reduce gut pathogen infection in the common eastern bumble bee. *Functional Ecology*. 00:1-13. [(link)](https://doi.org/10.1111/1365-2435.14320)

**Fowler AE**, Sadd BM, Bassingthwaite T, Irwin RE, Adler LS. 2022. Consuming sunflower pollen reduced pathogen infection but did not alter measures of immunity in bumble bees. *Philosophical Transactions of the Royal Society B: Biological Sciences*. 377: 20210160. [(link)](https://royalsocietypublishing.org/doi/10.1098/rstb.2021.0160#.YnAFlFj0Pyc.twitter)

**Fowler AE**, Giacomini JJ, Connon SJ, Irwin RE, Adler LS. 2022. Sunflower pollen reduces a gut pathogen in the model bee species, *Bombus impatiens*, but has weaker effects in three wild congeners. *Proceedings of the Royal Society B*. 298(1968). <br/>

**Fowler AE**, Stone EC, Irwin RE, Adler LS. 2020. Sunflower pollen reduces a gut pathogen in worker and queen but not male bumble bees. *Ecological Entomology*. 45(6):1318-1326. <br/>

Adler LS, **Fowler AE**, Malfi RL, Anderson PR, Coppinger LM, Deneen PM, Lopez S, Irwin RE, Farrell IW, Stevenson PC. 2020. Assessing chemical mechanisms underlying the effects of sunflower pollen on a gut pathogen in bumble bees. *Journal of Chemical Ecology*. 46:649-658. <br/>

**Fowler AE**, Irwin RE, Adler LS. 2019. Parasite defense mechanisms in bees: behavior, immunity, antimicrobials, and symbionts. *Emerging Topics in Life Sciences*. 4(1):59-76. <br/>

Beasley DE, Fitzgerald J, **Fowler AE**, Keleher K, Lopez-Uribe MM, Dunn RR. 2019. Do Bee Wings Adapt for Flight in Urban Environments? *Southeastern Naturalist*. 18(2):183-191 <br/>

Youngsteadt E, Irwin RE, **Fowler AE**, Kunz M, Suiter D, Connon SJ, Bertone M, Sorenson C. 2018. Venus Flytrap rarely traps its pollinators. *American Naturalist*. 191:539-546. <br/>

**Fowler AE**, Lor D, Farrell C, Bauman M, Peterson MN, Langerhans RB. 2018. Predator loss leads to reduced antipredator behaviors in Bahamas Mosquitofish. *Evolutionary Ecology Research*. 19:378-405. 
